# Generated by Django 2.2.1 on 2019-06-05 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_documents'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Documents',
            new_name='Document',
        ),
    ]
