# Generated by Django 2.2.1 on 2019-06-05 23:22

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_auto_20190605_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=post.models.upload_file_loc),
        ),
    ]
