# Generated by Django 2.2.1 on 2019-06-05 23:37

import django.core.files.storage
from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_auto_20190605_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/home/caesar/django/learning/justdjango/blog/protected_media'), upload_to=post.models.upload_file_loc),
        ),
    ]
