# Generated by Django 2.2.1 on 2019-06-07 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_documentdownload'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentdownload',
            name='title',
            field=models.CharField(default='first', max_length=100),
            preserve_default=False,
        ),
    ]
