# Generated by Django 2.2.1 on 2019-06-07 03:15

import django.core.files.storage
from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0016_auto_20190607_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(default='hello', storage=django.core.files.storage.FileSystemStorage(location='/home/caesar/django/learning/justdjango/blog/protected_media'), upload_to=post.models.upload_file_loc),
            preserve_default=False,
        ),
    ]
