# Generated by Django 2.2.1 on 2019-06-10 23:02

from django.db import migrations, models
import post.models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0017_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(storage=storages.backends.s3boto3.S3Boto3Storage(location='protected'), upload_to=post.models.upload_file_loc),
        ),
    ]
