# Generated by Django 2.2.1 on 2019-06-11 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0018_auto_20190610_2302'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentDownload',
        ),
    ]
